"""menambahkan class user

Revision ID: 81767fd3b763
Revises: 
Create Date: 2024-09-17 11:41:44.351983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81767fd3b763'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('rombongan', sa.String(length=2), nullable=True),
    sa.Column('gambar', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
