"""membuat tabel user dan rombel

Revision ID: 8d5a7f616bce
Revises: 
Create Date: 2024-09-19 12:05:56.787650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d5a7f616bce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rombel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=50), nullable=True),
    sa.Column('rombel_id', sa.Integer(), nullable=False),
    sa.Column('gambar', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['rombel_id'], ['rombel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('rombel')
    # ### end Alembic commands ###
