"""menambahkan class rombel dan ForeignKey class user ke rombel

Revision ID: a429340f2973
Revises: 81767fd3b763
Create Date: 2024-09-19 11:43:07.555276

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a429340f2973'
down_revision = '81767fd3b763'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rombel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nama', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('rombel_id', sa.Integer(), nullable=False))
        batch_op.alter_column('gambar',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'rombel', ['rombel_id'], ['id'])
        batch_op.drop_column('name')
        batch_op.drop_column('rombongan')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rombongan', mysql.VARCHAR(length=2), nullable=True))
        batch_op.add_column(sa.Column('name', mysql.VARCHAR(length=128), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('gambar',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.drop_column('rombel_id')
        batch_op.drop_column('nama')

    op.drop_table('rombel')
    # ### end Alembic commands ###
